# Generated by Django 4.2.6 on 2023-10-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default/default-avatar.png', upload_to='users/', verbose_name='Avatar'),
        ),
    ]
