# Generated by Django 4.2.6 on 2023-11-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_promocode_cartproduct_cart_promo_cart_user'),
        ('account', '0003_user_address_user_city_user_country_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='users', to='shop.product', verbose_name='Favorites'),
        ),
    ]
