# Generated by Django 4.2.6 on 2023-10-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default/default-category.png', upload_to='category/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='default/default-product.jpg', upload_to='products/', verbose_name='Image'),
        ),
    ]
